name: somanystories
favicon: null
layout_spectrum: 0.7946242913603783
typography_spectrum: 0.07312658475711942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5743394596502185
  lightness: 0.1099949034396559
  saturation: 0.19390572258271277
  rhythmicContrast: 0.9288556871470064
purpose: []
