name: somanystories
favicon: null
layout_spectrum: 0.94241
typography_spectrum: 0.07312658475711942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8a361'
    - '#090907'
    - '#f7442d'
    - '#763c28'
    - '#9c712d'
  brandStrength: 0.5743394596502185
  lightness: 0.1099949034396559
  saturation: 0.19390572258271277
  rhythmicContrast: 0.9288556871470064
purpose: []
